language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - develop
    - master

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
  - echo 'extension = ldap.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

addons:
  apt:
    packages:
      - slapd

script: phpunit
